"""EPG source configuration and country mappings."""
COUNTRY_SITE_PREFIXES = [
    "hu", "de", "at", "ch", "fr", "it", "es", "uk", "gb",
    "ro", "cz", "sk", "pl", "nl", "be", "pt",
    "se", "no", "dk", "fi", "gr", "tr", "rs", "hr", "si", "bg",
    "al", "ie", "us", "ca", "au", "ru", "br",
]

_CATEGORY_TO_COUNTRY: dict[str, str] = {
    "austria": "at", "österreich": "at", "osztrák": "at",
    "belgium": "be", "belga": "be",
    "bulgaria": "bg", "bolgár": "bg",
    "switzerland": "ch", "schweiz": "ch", "suisse": "ch", "svájc": "ch",
    "czech": "cz", "czechia": "cz", "cseh": "cz",
    "germany": "de", "deutschland": "de", "német": "de", "german": "de",
    "denmark": "dk", "dán": "dk",
    "spain": "es", "españa": "es", "spanyol": "es",
    "france": "fr", "francia": "fr", "french": "fr",
    "united kingdom": "gb", "uk": "gb", "great britain": "gb", "britain": "gb", "england": "gb", "angol": "gb",
    "greece": "gr", "görög": "gr",
    "hungary": "hu", "hungarian": "hu", "magyar": "hu", "magyarország": "hu",
    "croatia": "hr", "horvát": "hr",
    "ireland": "ie", "ír": "ie",
    "italy": "it", "italia": "it", "olasz": "it", "italian": "it",
    "netherlands": "nl", "holland": "nl",
    "norway": "no", "norvég": "no",
    "poland": "pl", "lengyel": "pl", "polish": "pl",
    "portugal": "pt", "portugál": "pt",
    "romania": "ro", "románia": "ro", "román": "ro",
    "serbia": "rs", "szerb": "rs",
    "sweden": "se", "svéd": "se",
    "slovenia": "si", "szlovén": "si",
    "slovakia": "sk", "szlovák": "sk",
    "turkey": "tr", "török": "tr", "turkish": "tr",
    "usa": "us", "america": "us", "amerikai": "us",
    "canada": "ca", "kanada": "ca",
    "australia": "au", "ausztrál": "au",
    "russia": "ru", "orosz": "ru", "russian": "ru",
    "brasil": "br", "brazil": "br",
    "albania": "al", "albán": "al",
    "finland": "fi", "finn": "fi",
}

_EPG_SOURCES: dict[str, list[str]] = {
    "at": ["https://www.open-epg.com/files/austria.xml", "https://www.free-epg.de/api/epg/at.xml.gz", "https://iptv-epg.org/files/epg-at.xml"],
    "de": ["https://www.free-epg.de/api/epg/de.xml.gz", "https://iptv-epg.org/files/epg-de.xml"],
    "ch": ["https://www.free-epg.de/api/epg/ch.xml.gz", "https://iptv-epg.org/files/epg-ch.xml"],
    "fr": ["https://www.open-epg.com/files/france.xml"],
    "it": ["https://www.open-epg.com/files/italy.xml", "https://www.free-epg.de/api/epg/rytec/it.xml", "https://iptv-epg.org/files/epg-it.xml"],
    "es": ["https://www.open-epg.com/files/spain.xml"],
    "gb": ["https://www.open-epg.com/files/unitedkingdom.xml"],
    "ro": ["https://www.open-epg.com/files/romania.xml", "https://www.free-epg.de/api/epg/rytec/ro.xml", "https://iptv-epg.org/files/epg-ro.xml"],
    "cz": ["https://www.open-epg.com/files/czechrepublic.xml"],
    "sk": ["https://www.open-epg.com/files/slovakia.xml"],
    "pl": ["https://www.open-epg.com/files/poland.xml"],
    "nl": ["https://www.open-epg.com/files/netherlands.xml"],
    "be": ["https://www.open-epg.com/files/belgium.xml"],
    "pt": ["https://www.open-epg.com/files/portugal.xml"],
    "se": ["https://www.open-epg.com/files/sweden.xml"],
    "no": ["https://www.open-epg.com/files/norway.xml"],
    "dk": ["https://www.open-epg.com/files/denmark.xml"],
    "fi": ["https://www.open-epg.com/files/finland.xml"],
    "gr": ["https://www.open-epg.com/files/greece.xml"],
    "tr": ["https://www.open-epg.com/files/turkey.xml"],
    "rs": ["https://www.open-epg.com/files/serbia.xml"],
    "hr": ["https://www.open-epg.com/files/croatia.xml"],
    "si": ["https://www.open-epg.com/files/slovenia.xml"],
    "bg": ["https://www.open-epg.com/files/bulgaria.xml"],
    "al": ["https://www.open-epg.com/files/albania.xml"],
    "hu": ["https://iptv-epg.org/files/epg-hu.xml"],
    "ie": ["https://www.open-epg.com/files/ireland.xml"],
    "us": ["https://www.open-epg.com/files/usa.xml"],
    "ca": ["https://www.open-epg.com/files/canada.xml"],
    "au": ["https://www.open-epg.com/files/australia.xml"],
    "ru": ["https://www.open-epg.com/files/russia.xml"],
    "br": ["https://www.open-epg.com/files/brazil.xml"],
}
