export interface RadioStation {
  key: string;
  name: string;
  streamUrl: string;
  logo: string;
  metadataUrl?: string;
}

export const USE_RADIO_API = true;

export const radioStations: RadioStation[] = [
  { key: 'radio_0', name: 'Aktív Rádió 92.2', streamUrl: 'http://aktivradio.hu:8000/aktiv.mp3', logo: 'http://www.popularis.hu/radio/aktiv.png' },
  { key: 'radio_1', name: 'Balaton Rádió 88.7', streamUrl: 'http://91.82.85.41:8200/listen.pls', logo: 'http://www.balatonfm.hu///templates/br14/favicon.ico' },
  { key: 'radio_2', name: 'Balatonica Radio', streamUrl: 'http://balatonica.hu:8000/stream_high', logo: 'http://www.balatonica.hu//themes/2017/assets/ico/favicon.ico' },
  { key: 'radio_3', name: 'Bartók Rádió', streamUrl: 'http://mr-stream.mediaconnect.hu/4742/mr3hq.mp3', logo: 'http://operavilag.net/wp-content/uploads/hirmondo-kaleidoszkop/2013/09/24/11921/bartok_radio_thumb.png' },
  { key: 'radio_4', name: 'BDPST ROCK', streamUrl: 'http://stream.bdpstrock.hu/bdpstrock_192k', logo: 'https://bdpstrock.hu/assets/img/front/favicon.ico' },
  { key: 'radio_5', name: 'Best FM', streamUrl: 'http://stream.webthings.hu:8000/fm95-x-128.mp3', logo: 'http://www.popularis.hu/radio/radio-fm-95.png' },
  { key: 'radio_6', name: 'Bithang Yoo Rádió', streamUrl: 'http://stream.diazol.hu:35160/live.mp3', logo: 'https://cdn.onlineradiobox.com/img/l/2/78492.v6.png' },
  { key: 'radio_7', name: 'Buddha FM', streamUrl: 'http://libretime.buddhafm.hu:4000/buddhafm', logo: 'https://www.buddhafm.hu/wp-content/uploads/2021/07/cropped-android-chrome-512x512-1-180x180.png' },
  { key: 'radio_8', name: 'Callisto', streamUrl: 'http://188.165.11.30:4500/live.mp3', logo: 'https://www.radio.net/images/broadcasts/02/45/1467/c300.png' },
  { key: 'radio_9', name: 'Civil Rádió', streamUrl: 'http://civilradio.hu:8000/;stream', logo: 'http://sos.civilradio.hu/wp-content/uploads/dynamik-gen/theme/images/civil-foot.png' },
  { key: 'radio_10', name: 'Club Dance Online', streamUrl: 'https://stream.clubdance.online:8000/live.mp3', logo: 'https://clubdance.online/wp-content/uploads/2015/08/Clubdanceonlinelogo2-300x139.png' },
  { key: 'radio_11', name: 'Cool FM', streamUrl: 'http://mediagw.e-tiger.net/stream/cfmhq', logo: 'https://onlinestream.live/logos/5386.png' },
  { key: 'radio_12', name: 'Cool FM Goldies', streamUrl: 'http://mediagw.e-tiger.net:8000/stream/goldhq', logo: 'https://cdn-profiles.tunein.com/s288308/images/logog.png?t=1653525921000' },
  { key: 'radio_13', name: 'Cool FM kultX', streamUrl: 'http://mediagw.e-tiger.net/stream/krehq', logo: 'https://zeno.fm/radio/coolfm-kultx-online/' },
  { key: 'radio_14', name: 'Cool FM Xbeat', streamUrl: 'http://mediagw.e-tiger.net/stream/xbeathq', logo: 'https://cdn-profiles.tunein.com/s169655/images/logog.png?t=1653527051000' },
  { key: 'radio_15', name: 'COOLFM 2000-es évek', streamUrl: 'https://mediagw.e-tiger.net/stream/zc03', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/2000s.jpg' },
  { key: 'radio_16', name: 'COOLFM 2010-es évek', streamUrl: 'https://mediagw.e-tiger.net/stream/zc02', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/2010s.jpg' },
  { key: 'radio_17', name: 'COOLFM 90-es évek', streamUrl: 'https://mediagw.e-tiger.net/stream/zc05', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/90s.jpg' },
  { key: 'radio_18', name: 'COOLFM Acoustic', streamUrl: 'https://mediagw.e-tiger.net/stream/zc12', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/acoustic.jpg' },
  { key: 'radio_19', name: 'COOLFM Best Hits EVER', streamUrl: 'https://mediagw.e-tiger.net/stream/zc11', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/best-hits-ever.jpg' },
  { key: 'radio_20', name: 'COOLFM Bside/Alternative', streamUrl: 'https://mediagw.e-tiger.net/stream/zc16', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/bside.jpg' },
  { key: 'radio_21', name: 'COOLFM Chill', streamUrl: 'https://mediagw.e-tiger.net/stream/zc24', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/chill.jpg' },
  { key: 'radio_22', name: 'COOLFM Classic Rock', streamUrl: 'https://mediagw.e-tiger.net/stream/zc10', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/rock.jpg' },
  { key: 'radio_23', name: 'COOLFM Funky&Soul', streamUrl: 'https://mediagw.e-tiger.net/stream/zc25', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/funky.jpg' },
  { key: 'radio_24', name: 'COOLFM Hazai Kedvencek', streamUrl: 'https://mediagw.e-tiger.net/stream/zc19', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/hazai-kedvencek.jpg' },
  { key: 'radio_25', name: 'COOLFM Jazz', streamUrl: 'https://mediagw.e-tiger.net/stream/zc13', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/jazz.jpg' },
  { key: 'radio_26', name: 'COOLFM Karácsonyi Dalok', streamUrl: 'https://mediagw.e-tiger.net/stream/zc27', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/christmas.jpg' },
  { key: 'radio_27', name: 'COOLFM Love Songs', streamUrl: 'https://mediagw.e-tiger.net/stream/zc21', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/love-songs.jpg' },
  { key: 'radio_28', name: 'COOLFM Nyári Slágerek', streamUrl: 'https://mediagw.e-tiger.net/stream/zc09', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/summer-hits.jpg' },
  { key: 'radio_29', name: 'COOLFM Party', streamUrl: 'https://mediagw.e-tiger.net/stream/zc18', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/party.jpeg' },
  { key: 'radio_30', name: 'COOLFM Sportoláshoz', streamUrl: 'https://mediagw.e-tiger.net/stream/zc20', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/sport.jpg' },
  { key: 'radio_31', name: 'COOLFM World Music', streamUrl: 'https://mediagw.e-tiger.net/stream/zc26', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/world-music.jpg' },
  { key: 'radio_32', name: 'COOLFM YouTube HOT HITS!', streamUrl: 'https://mediagw.e-tiger.net/stream/zc22', logo: 'https://coolfm.hu/radio/wp-content/uploads/2021/01/youtube.jpg' },
  { key: 'radio_33', name: 'Csillagpont Rádió 94.0', streamUrl: 'http://streamer1.borsodweb.hu:48000/csillagpont', logo: 'https://www.csillagpontradio.hu/sites/www.csillagpontradio.hu/themes/cspr_bootstrap/logo.png' },
  { key: 'radio_34', name: 'Dance Wave Retro!', streamUrl: 'http://stream.dancewave.online:8080/retrodance.mp3', logo: 'http://retro.dancewave.online/dw-logo_s.png' },
  { key: 'radio_35', name: 'Dance Wave!', streamUrl: 'http://stream2.dancewave.online:8080/dance.ogg', logo: 'http://dancewave.online/dw-logo_s.png' },
  { key: 'radio_36', name: 'DANCEable Radio', streamUrl: 'http://176.31.244.83:35944/listen.pls', logo: 'https://myradiostream.com/station/uploads/logo/f576ba66ca87d279b1d5093843b3d7a48ac53c90.png' },
  { key: 'radio_37', name: 'Dankó Rádió', streamUrl: 'http://mr-stream.mediaconnect.hu/4747/mr7.aac', logo: 'http://radjo.hu/wp-content/uploads/2015/04/Danko-Radio-Online.jpg' },
  { key: 'radio_38', name: 'Danubius Rádió', streamUrl: 'https://stream.danubiusradio.hu/danubius_320k', logo: 'https://play-lh.googleusercontent.com/ryU4uW58pPU1mIpsOqyH4gD-x1pwa3XDyS9UetN71fqg-lQjbPCkN1MHxXsTVBx6dxw=w600-h300-pc0xffffff-pd' },
  { key: 'radio_39', name: 'Deep House', streamUrl: 'https://stream1.rdstrm.com/deep-house-radio-dance-music.mp3', logo: 'https://myonlineradio.hu/public/uploads/radio_img/dance-music/play_250_250.webp' },
  { key: 'radio_40', name: 'Disco Diamond Radio', streamUrl: 'http://discodiamond.radioca.st/stream', logo: 'https://discodiamondradio.eu/m/index_htm_files/701.jpg' },
  { key: 'radio_41', name: 'Dráva Hullám 102.7', streamUrl: 'http://hosting2.42netmedia.com:13070/stream', logo: 'https://static-media.streema.com/media/cache/c3/9b/c39b71464647c1833d3a47909c1db7e0.jpg' },
  { key: 'radio_42', name: 'Duna World Rádió', streamUrl: 'http://mr-stream.mediaconnect.hu/4760/dwr.aac', logo: 'https://upload.wikimedia.org/wikipedia/hu/thumb/5/56/DW_radio.png/250px-DW_radio.png' },
  { key: 'radio_43', name: 'EFM', streamUrl: 'http://radioe.net:8080/efm_hd', logo: 'http://efm.hu/wp-content/uploads/2021/09/cropped-ico-180x180.png' },
  { key: 'radio_44', name: 'Fáklya Rádió', streamUrl: 'https://faklyaradio.hu/stream2/', logo: 'https://myonlineradio.hu/public/uploads/radio_img/faklya-radio/play_250_250.webp' },
  { key: 'radio_45', name: 'FM90 Campus Rádió', streamUrl: 'http://stream.fm90.hu:8000/listen.pls', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx-Q5PUcZefZkFEQ6qkRQEk4x6on9H6VLU3w&s' },
  { key: 'radio_46', name: 'Folkrádio', streamUrl: 'https://stream.folkradio.hu/folkradio.mp3', logo: 'https://www.folkradio.hu//favicon.ico' },
  { key: 'radio_47', name: 'Forrás Radio 97.8', streamUrl: 'http://91.82.85.44:1630/forrasradio.mp3', logo: 'https://play-lh.googleusercontent.com/G0ONoW2flt9JZKi28aQivt9N0CdH5OYYCQDxhu9gmTsX-MDqjpZ01rkuJBziyvHlMN0' },
  { key: 'radio_48', name: 'Friss 93.4', streamUrl: 'http://stream.frissfm.hu:10050/listen.pls', logo: 'http://frissfm.hu/favicon/apple-touch-icon.png' },
  { key: 'radio_49', name: 'Gong Rádió', streamUrl: 'http://stream.gongradio.hu:8000/gong-fm.mp3', logo: 'http://www.gong.hu/images2/android-icon-192x192.png' },
  { key: 'radio_50', name: 'Tordas Rádió', streamUrl: 'http://stream.tilos.hu:8000/tordas_radio_online', logo: 'https://static.wixstatic.com/media/e462c5_1e9f37f367b00c91e2cb96051c817a53.jpg/v1/fill/w_92,h_92,al_c,q_80,usm_0.66_1.00_0.01/e462c5_1e9f37f367b00c91e2cb96051c817a53.webp' },
  { key: 'radio_51', name: 'Hir FM 95.3', streamUrl: 'https://n43a-eu.rcs.revma.com/wevb267khf9uv?rj-ttl=5&rj-tok=AAABlP61Qh0Ae9ZnibOGhBGN0g', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNBo-Bnza5giVsZ530jIRpUHPpX8RI3P_a1fNsqoSIu3rBaINBYxLiwEajUj9-qlJoiwo&usqp=CAU' },
  { key: 'radio_52', name: 'Hobby Rádió', streamUrl: 'http://www.hobbyradio.hu:8000/hobbyradio.mp3', logo: 'https://hobbyradio.hu/wp-content/themes/hobby2/img/icon.png' },
  { key: 'radio_53', name: 'I Love Pécs Rádió', streamUrl: 'http://radio.ilovepecs.hu:8200/ilp.mp3', logo: 'https://www.google.com/s2/favicons?sz=256&domain=radio.ilovepecs.hu' },
  { key: 'radio_54', name: 'Insane', streamUrl: 'http://radio.newinsane.info/', logo: 'https://cdn.onlineradiobox.com/img/fblogo/2/36432.v1.png' },
  { key: 'radio_55', name: 'Jazzradio.hu', streamUrl: 'https://www.jazzradio.hu:8000/jazzradio_192.ogg', logo: 'https://www.jazzradio.hu/wp-content/uploads/2018/06/open_5.jpg' },
  { key: 'radio_56', name: 'Karc FM 105.9', streamUrl: 'http://92.61.114.191:13100/stream', logo: 'https://www.radio.net/images/broadcasts/07/c3/38655/2/c300.png' },
  { key: 'radio_57', name: 'Klasszik Rádió 92.1', streamUrl: 'http://s04.diazol.hu:9600/live.mp3', logo: 'https://cdn-profiles.tunein.com/s122915/images/logog.jpg?t=1' },
  { key: 'radio_58', name: 'Klubrádió', streamUrl: 'http://hu-stream03.klubradio.hu:8080/bpstream', logo: 'http://www.popularis.hu/radio/klub.png' },
  { key: 'radio_59', name: 'KORONAfm100 100.0', streamUrl: 'http://82.141.165.6:8000/;stream', logo: 'https://www.koronafm100.hu/wp-content/uploads/2020/03/cropped-faviconkorona-192x192.png' },
  { key: 'radio_60', name: 'Kossuth 107.8', streamUrl: 'https://icast.connectmedia.hu/4736/mr1.mp3', logo: 'https://www.radio.net/images/broadcasts/22/50/5196/c300.png' },
  { key: 'radio_61', name: 'Lahmacun Radio', streamUrl: 'https://streaming.lahmacun.hu/radio/8000/radio.mp3', logo: 'https://www.lahmacun.hu/wp-content/uploads/lahmalogo-1024x1024.jpg' },
  { key: 'radio_62', name: 'Lakihegy Rádió 107.0', streamUrl: 'http://lakihegyradio.hu/player/stream.php', logo: 'https://www.budaorsiinfo.hu/wp-content/uploads/2014/01/lakihegy_radiologo.jpg' },
  { key: 'radio_63', name: 'Látszótér', streamUrl: 'http://stream.latszoter.hu:8000/radio', logo: 'https://latszoter.hu/sites/all/themes/latszoter_theme/logo.png' },
  { key: 'radio_64', name: 'Laza Rádió', streamUrl: 'http://stream.lazaradio.com:8100/live.ogg', logo: 'https://lazaradio.com/favicon.ico' },
  { key: 'radio_65', name: 'Lépés Rádió', streamUrl: 'http://stream.lepesradio.hu:4000/live.mp3', logo: 'https://lepesradio.hu/images/logo_jsn_neon_2.png' },
  { key: 'radio_66', name: 'Luxfunk Blackmix', streamUrl: 'http://188.165.11.30:5000/luxfunkblackmix.mp3', logo: 'https://www.luxfunkradio.com/wp-content/uploads/2017/01/cropped-luxfunk_logo_icon-270x270.png' },
  { key: 'radio_67', name: 'Luxfunk Dance', streamUrl: 'http://188.165.11.30:5000/luxfunkdance.mp3', logo: 'https://www.luxfunkradio.com/wp-content/uploads/2017/01/cropped-luxfunk_logo_icon-270x270.png' },
  { key: 'radio_68', name: 'Luxfunk Radio', streamUrl: 'http://188.165.11.30:5000/luxfunkradio.mp3', logo: 'https://www.luxfunkradio.com/wp-content/uploads/2017/01/cropped-luxfunk_logo_icon-270x270.png' },
  { key: 'radio_69', name: 'Magic Disco', streamUrl: 'http://stream1.virtualisan.net:4420/live.mp3', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWr-K3m6Evb6BWI-Q_OUz5ZYH--rDpxaV6BQ&s' },
  { key: 'radio_70', name: 'Magic Disco Radio', streamUrl: 'http://188.165.11.30:4420/live.mp3', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWr-K3m6Evb6BWI-Q_OUz5ZYH--rDpxaV6BQ&s' },
  { key: 'radio_71', name: 'Magic Disco Rádió', streamUrl: 'http://live2.magicdiscoradio.com:4420/live.mp3', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWr-K3m6Evb6BWI-Q_OUz5ZYH--rDpxaV6BQ&s' },
  { key: 'radio_72', name: 'Magyar Katolikus Rádió', streamUrl: 'http://katolikusradio.hu:9000/live_hi.mp3', logo: 'http://www.katolikusradio.hu/uploads/content/164/kepek/c_matrica.png' },
  { key: 'radio_73', name: 'Manna 98.6', streamUrl: 'http://icast.connectmedia.hu/4780/live.mp3', logo: 'https://mannafm.hu/wp-content/uploads/2019/01/mannafm-ikon-300x300.jpg' },
  { key: 'radio_74', name: 'Mária Rádió', streamUrl: 'http://honlap.mariaradio.hu:8000/mr', logo: 'http://www.mariaradio.hu/favicon.ico' },
  { key: 'radio_75', name: 'Maxi Rádió', streamUrl: 'http://46.107.212.101:9240/live', logo: 'https://myonlineradio.hu/public/uploads/radio_img/maxiradio/play_250_250.png' },
  { key: 'radio_76', name: 'Mega Live 100.2', streamUrl: 'https://mega-live.net:2053/live.mp3', logo: 'https://myonlineradio.hu/public/uploads/radio_img/megalive-radio/play_250_250.webp' },
  { key: 'radio_77', name: 'Mega Rádió', streamUrl: 'https://megaradio.hu/megastream', logo: 'http://www.megaradio.hu/wp-content/uploads/2018/01/MEGA-OROSHAZA-LOGO-267x300.png' },
  { key: 'radio_78', name: 'MegaDance', streamUrl: 'https://gamershouse.hu:8080/livemega.mp3', logo: 'https://static.tuneyou.com/images/logos/500_500/47/1647/MegaDanceRadio_1.jpg' },
  { key: 'radio_79', name: 'Mera', streamUrl: 'https://stream.radio.co/s3fd8d173f/listen', logo: 'https://seeded-session-images.scdn.co/v2/img/540/r/artist/2U4kDk5SJvlKtJukUSLlQl/en' },
  { key: 'radio_80', name: 'Mercy Rádió', streamUrl: 'http://stream.mercyradio.eu/mercyradio.mp3', logo: 'http://mercyradio.eu/wp-content/uploads/2014/02/fredy-mediapartner.png' },
  { key: 'radio_81', name: 'Mercy Rádió Kabaré', streamUrl: 'http://stream.mercyradio.eu/kabare.mp3', logo: 'http://mercyradio.eu/wp-content/uploads/2014/02/fredy-mediapartner.png' },
  { key: 'radio_82', name: 'Mercy Rádió Mulatós', streamUrl: 'http://stream.mercyradio.eu/mulatos.mp3', logo: 'http://mercyradio.eu/wp-content/uploads/2014/02/fredy-mediapartner.png' },
  { key: 'radio_83', name: 'Mex Deejay', streamUrl: 'http://s01.diazol.hu:35000/live.mp3', logo: 'https://static.mytuner.mobi/media/tvos_radios/wr2j7ns4vnzz.jpg' },
  { key: 'radio_84', name: 'Méz Rádió 103.1', streamUrl: 'http://stream.mezradio.hu:7812/mezfm128.mp3', logo: 'http://www.mezradio.hu/assets/images/mr.ico' },
  { key: 'radio_85', name: 'miradionk.hu', streamUrl: 'http://92.61.114.191:6030/listen.pls', logo: 'http://magyarzene.eu/wp-content/uploads/2014/06/MIRADIONK.jpg' },
  { key: 'radio_86', name: 'MixRadio Fresh', streamUrl: 'http://adas.adasszerver.hu/live', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSppXz2yfH2erS5r-AAuK7LL4RZNujEKXZYQw&s' },
  { key: 'radio_87', name: 'Mustár Rádió', streamUrl: 'http://193.138.125.14:8500/listen.pls', logo: 'http://mustarhaz.hu/wp-content/uploads/8766.jpg' },
  { key: 'radio_88', name: 'Nemzetiségi adások', streamUrl: 'http://mr-stream.mediaconnect.hu/4743/mr4.aac', logo: 'https://upload.wikimedia.org/wikipedia/hu/archive/8/8e/20120820103558!Mr4-Nemzetis%C3%A9gi.png' },
  { key: 'radio_89', name: 'Next FM', streamUrl: 'https://stream.nextfm.hu/radio/8000/nextfmhu.mp3?1590416039', logo: 'https://nextfm.hu/wp-content/uploads/2021/11/cropped-nextfm70-1-1-180x180.png' },
  { key: 'radio_90', name: 'NNK Crazy Club', streamUrl: 'http://radio.nnkcrazyclub.hu:7163/crazyklub', logo: 'https://cdn-profiles.tunein.com/s280618/images/logog.png?t=151498' },
  { key: 'radio_91', name: 'Open Air Radio', streamUrl: 'http://79.172.209.223:9200/stream', logo: 'http://m.cdn.blog.hu/mu/musicpress/image/openair-logo2a.jpg' },
  { key: 'radio_92', name: 'Opera Radio Budapest', streamUrl: 'http://onair7.xdevel.com:7126/1/', logo: 'https://online-radio.eu/logo/19/19411.jpg' },
  { key: 'radio_93', name: 'Oxygen', streamUrl: 'https://oxygenmusic.hu:8443/oxygenmusic', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcaxbS4UlvR6T7-YLX2Bw3BaZz25lo18_uBw&s' },
  { key: 'radio_94', name: 'Oxygen Black Music', streamUrl: 'https://oxygenmusic.hu:8443/blackmusic_128', logo: 'https://oxygenmusic.hu/favicon.ico' },
  { key: 'radio_95', name: 'Oxygen Classic Rock', streamUrl: 'https://oxygenmusic.hu:8443/oxygenclassicrock', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/rock_web_cover.jpg' },
  { key: 'radio_96', name: 'Oxygen Classics', streamUrl: 'https://oxygenmusic.hu:8443/Classic_128', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/klasszikus_zene_web_cover.jpg' },
  { key: 'radio_97', name: 'Oxygen Fitness', streamUrl: 'https://oxygenmusic.hu:8443/oxygenfitness', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/fitness_web_cover.jpg' },
  { key: 'radio_98', name: 'Oxygen Happy', streamUrl: 'https://oxygenmusic.hu:8443/oxygenhappy', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/happy_music_web_cover.jpg' },
  { key: 'radio_99', name: 'Oxygen Indie', streamUrl: 'https://oxygenmusic.hu:8443/oxygenindie', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/indie_hits_web_cover.jpg' },
  { key: 'radio_100', name: 'Oxygen Italo Hits', streamUrl: 'https://oxygenmusic.hu:8443/oxygenitalohits', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/italo_hits_web_cover.jpg' },
  { key: 'radio_101', name: 'Oxygen Kids', streamUrl: 'https://oxygenmusic.hu:8443/oxygenkids', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/kids_web_cover.jpg' },
  { key: 'radio_102', name: 'Oxygen Lounge', streamUrl: 'https://oxygenmusic.hu:8443/oxygenlounge', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/lounge_web_cover.jpg' },
  { key: 'radio_103', name: 'Oxygen Love Songs', streamUrl: 'https://oxygenmusic.hu:8443/oxygenlovesongs', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/love_songs_web_cover.jpg' },
  { key: 'radio_104', name: 'Oxygen Magyar Zene', streamUrl: 'https://oxygenmusic.hu:8443/oxygenmagyarzene', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/magyar_zene_web_cover.jpg' },
  { key: 'radio_105', name: 'Oxygen Music', streamUrl: 'https://oxygenmusic.hu:8443/oxygenmusic_192', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/oxygen_music_web_cover.jpg' },
  { key: 'radio_106', name: 'Oxygen Oldies', streamUrl: 'https://oxygenmusic.hu:8443/oxygenoldies', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/oldies_web_cover.jpg' },
  { key: 'radio_107', name: 'Oxygen Spencer-Hill', streamUrl: 'https://oxygenmusic.hu:8443/oxygenspencerhillzenek', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/spenser_hill_web_cover.jpg' },
  { key: 'radio_108', name: 'Oxygen The 10s Hits', streamUrl: 'https://oxygenmusic.hu:8443/oxygenthe10shits', logo: 'https://cdn1.umg3.net/587/files/2018/09/5-2.jpg' },
  { key: 'radio_109', name: 'Oxygen The 80s Hits', streamUrl: 'https://oxygenmusic.hu:8443/oxygenthe80shits', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/the_80_hits_web_cover.jpg' },
  { key: 'radio_110', name: 'Oxygen The 90s Hits', streamUrl: 'https://oxygenmusic.hu:8443/oxygenthe90shits', logo: 'https://oxygenmusic.hu/logo192.png' },
  { key: 'radio_111', name: 'Ozone FM', streamUrl: 'https://oxygenmusic.hu:8443/ozonefm_128.mp3', logo: 'https://oxygenmusic.hu/wp-content/uploads/2021/02/ozone_fm_web_cover.jpg' },
  { key: 'radio_112', name: 'Pannónia Rádió', streamUrl: 'http://kft.kesintisizyayin.com:8130/stream', logo: 'http://pannoniaradio.hu/wp-content/uploads/2018/11/cropped-44313007_284544652155835_7109065280344555520_n-270x270.jpg' },
  { key: 'radio_113', name: 'Parlamenti adások', streamUrl: 'http://mr-stream.mediaconnect.hu/4745/mr5.aac', logo: 'http://db.radioline.fr/pictures/radio_04af649906b08d48b1e16c19cbeefec4/logo200.jpg?size=200' },
  { key: 'radio_114', name: 'Pécs Aktuál Rádió 101.7', streamUrl: 'https://stream.pecsaktual.hu/paradio.mp3', logo: 'https://pecsaktual.hu/wp-content/uploads/2020/03/cropped-favicon-300x300.gif' },
  { key: 'radio_115', name: 'Periszkóp Rádió', streamUrl: 'http://sztrim.periszkopradio.hu:8088/;stream', logo: 'http://periszkopradio.hu/periweb/hatterkepek/logo-1.png' },
  { key: 'radio_116', name: 'Pesti Kabaré', streamUrl: 'https://eapps-cs.herokuapp.com/radio.pestikabare.hu', logo: 'http://pestikabare.hu/pestikabare.hu/logo.jpg' },
  { key: 'radio_117', name: 'Petőfi Rádió', streamUrl: 'http://mr-stream.mediaconnect.hu/4737/mr2.aac', logo: 'https://yt3.ggpht.com/-GTJ2bxBQj30/AAAAAAAAAAI/AAAAAAAAAAA/iVfktSbpM9c/s900-c-k-no-mo-rj-c0xffffff/photo.jpg' },
  { key: 'radio_118', name: 'Poptarisznya', streamUrl: 'http://adas.poptarisznya.hu:8200/live.mp3', logo: 'http://www.ahu.hu/images/stories/poptarisznya-facebook.jpg' },
  { key: 'radio_119', name: 'Poptarisznya Blues24', streamUrl: 'http://adas.poptarisznya.hu:8200/blues.mp3', logo: 'https://cdn.onlineradiobox.com/img/logo/6/77516.v2.png' },
  { key: 'radio_120', name: 'Poptarisznya Oldies', streamUrl: 'http://adas.poptarisznya.hu:8200/oldies.mp3', logo: 'https://cdn-profiles.tunein.com/s261429/images/logog.jpg?t=1' },
  { key: 'radio_121', name: 'Power FM', streamUrl: 'http://s39.myradiostream.com:11590/listen/;.mp3', logo: 'http://www.powerfm.hu/assets/images/logo.png' },
  { key: 'radio_122', name: 'Rádió 1', streamUrl: 'https://icast.connectmedia.hu/5201/live.mp3', logo: 'https://www.radio.net/images/broadcasts/31/a3/103344/2/c300.png' },
  { key: 'radio_123', name: 'Rádió 1 Debrecen', streamUrl: 'http://91.82.85.44:8080/debrecenradiofm95', logo: 'http://graph.facebook.com/radio1debrecen/picture?type=large' },
  { key: 'radio_124', name: 'Rádió 1 Kiskunfélegyháza', streamUrl: 'http://siriusradio.hu:8500/relay_mobile_911', logo: 'https://static.mytuner.mobi/media/tvos_radios/370/radio-1-kiskunfelegyhaza.b688737f.png' },
  { key: 'radio_125', name: 'Rádió 7', streamUrl: 'http://netradio.radio7.hu:8300/stream.mp3', logo: 'http://4.bp.blogspot.com/-IX-c5PaKy8A/VYnOJXxzUlI/AAAAAAAAAGQ/mzmfSQG3tAc/s420/r2.png' },
  { key: 'radio_126', name: 'Rádió 88', streamUrl: 'http://stream.radio88.hu:8000/listen.pls', logo: 'http://www.radio88.hu/favicon.ico' },
  { key: 'radio_127', name: 'Rádió 88 Club', streamUrl: 'http://stream2.radio88.hu:8400/;stream', logo: 'http://www.radio88.hu/favicon.ico' },
  { key: 'radio_128', name: 'Rádió 88 Retro', streamUrl: 'http://stream1.radio88.hu:8300/;stream', logo: 'http://www.radio88.hu/favicon.ico' },
  { key: 'radio_129', name: 'Rádió 88 Top', streamUrl: 'http://stream3.radio88.hu:8500/;stream', logo: 'http://www.radio88.hu/favicon.ico' },
  { key: 'radio_130', name: 'Rádió Antritt', streamUrl: 'http://stream.radioantritt.hu:8000/Antritt', logo: 'https://mytuner.global.ssl.fastly.net/media/tvos_radios/befkzjuwpcsw.png' },
  { key: 'radio_131', name: 'Rádió Bézs', streamUrl: 'http://195.210.29.82:8001/bezs', logo: 'https://netradio.online/files/styles/media/public/logo/radio-bezs.jpg?itok=xCudnZgd' },
  { key: 'radio_132', name: 'Rádió Bézs 2', streamUrl: 'http://195.210.29.82:8002/bezs2', logo: 'https://netradio.online/files/styles/media/public/logo/radio-bezs.jpg?itok=xCudnZgd' },
  { key: 'radio_133', name: 'Rádió Dabas 93.4', streamUrl: 'http://stream3.virtualisan.net:7040/listen.pls', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStC3KEShib-PNpZV1eDVgar6pGNhQHJ7Fhzw&s' },
  { key: 'radio_134', name: 'Radio Maria', streamUrl: 'http://dreamsiteradiocp.com:8032/stream', logo: 'https://www.mariaradio.hu/favicon.ico' },
  { key: 'radio_135', name: 'Rádió Most', streamUrl: 'http://stream.radiomost.hu:8200/live.mp3', logo: 'http://www.liveonlineradio.net/wp-content/uploads/2014/12/Radio-Most.jpg' },
  { key: 'radio_136', name: 'Radio Q', streamUrl: 'http://93.189.113.165:8000/stream', logo: 'http://radioq.hu/wp-content/uploads/2020/04/cropped-favicon512-180x180.png' },
  { key: 'radio_137', name: 'Radio Sense', streamUrl: 'https://stream1.virtualisan.net/prx/4800/stream.mp3', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsfMGcaNxhm1wslaRnhYVHvzjH5qgL0zkDTZUa8rKWGmcGLRl15Lu2PhLpeOpskZ8rgYc&usqp=CAU' },
  { key: 'radio_138', name: 'Radiobrand', streamUrl: 'http://radiobrand.es:8084/', logo: 'https://radiobrand.eu/wp-content/uploads/2020/07/radiobrand_logo_webslogen.png' },
  { key: 'radio_139', name: 'radiOzora', streamUrl: 'http://trance.out.airtime.pro:8000/trance_a', logo: 'https://www.radio.net/images/broadcasts/70/eb/37814/1/c300.png' },
  { key: 'radio_140', name: 'radiOzora Chill', streamUrl: 'http://chill.out.airtime.pro:8000/chill_a', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcXcP6bXaZF5xBJrTwKgd_1dp1b8dtKlUe1w&s' },
  { key: 'radio_141', name: 'Regina Radio', streamUrl: 'http://proxima.shoutca.st:8023/live', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJloBHq0IaBOGkNyHAqGYYWb0_u9LdV4sV8_Oq4oRZSbg-xLiJ2DmQoo3_Ns8R8DiGcHk&usqp=CAU' },
  { key: 'radio_142', name: 'Retro Radio', streamUrl: 'https://icast.connectmedia.hu/5002/live.mp3', logo: 'https://retroradio.hu/wp-content/themes/retroradio/assets/dist/img/favicon/apple-icon-120x120.png' },
  { key: 'radio_143', name: 'Retro Rádió', streamUrl: 'https://icast.connectmedia.hu/5001/live.mp3/retroradio_aac_128.m4a', logo: 'https://retroradio.hu/wp-content/themes/retroradio/assets/dist/img/favicon/apple-icon-120x120.png' },
  { key: 'radio_144', name: 'Rise FM Deep', streamUrl: 'https://stream1.virtualisan.net/prx/8080/risefm_deephouse_hq', logo: 'https://static.mytuner.mobi/media/tvos_radios/106/rise-fm-deep.55af4705.png' },
  { key: 'radio_145', name: 'Sárvár Rádió 96.5', streamUrl: 'http://92.61.114.191:9651/listen.pls', logo: 'http://www.sarvarradio.hu/wp-content/uploads/2017/04/cropped-logo_fb-270x270.jpg' },
  { key: 'radio_146', name: 'Sirius Rádió 91.1', streamUrl: 'http://siriusradio.hu:8500/relay_911', logo: 'https://www.google.com/s2/favicons?sz=256&domain=siriusradio.hu' },
  { key: 'radio_147', name: 'Sláger FM', streamUrl: 'http://92.61.114.159:7812/slagerfm256.mp3', logo: 'https://www.radio.net/images/broadcasts/9a/cf/8897/1/c300.png' },
  { key: 'radio_148', name: 'Sola Rádió', streamUrl: 'http://188.165.11.30:7000/live.mp3', logo: 'https://kuasark.com/files/stations-logos/sola-radio.png' },
  { key: 'radio_149', name: 'Spirit FM', streamUrl: 'https://s02.diazol.hu:10052/spweb1.mp3', logo: 'https://spiritfm.hu/images/logo_uj.png' },
  { key: 'radio_150', name: 'Sunshine Dance', streamUrl: 'http://195.56.193.129:8120/;stream/1?icy=http', logo: 'https://www.sunshinefm.hu/img/dance_big.png' },
  { key: 'radio_151', name: 'Sunshine FM', streamUrl: 'http://195.56.193.129:8100/;stream/1', logo: 'https://www.sunshinefm.hu/img/sunshine_default_.png' },
  { key: 'radio_152', name: 'Sunshine Pop', streamUrl: 'http://195.56.193.129:8110/;stream/1?icy=http', logo: 'https://www.sunshinefm.hu/img/pop_big.png' },
  { key: 'radio_153', name: 'Super DJ Radio', streamUrl: 'http://stream.diazol.hu:35150/stream', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCScWGN25NKAxRIrhUkJFUdhqjgqnbxMRcrg&s' },
  { key: 'radio_154', name: 'Szentistván Rádió', streamUrl: 'http://online.szentistvanradio.hu:7000/adas', logo: 'https://myonlineradio.hu/public/uploads/radio_img/szent-istvan-radio/play_250_250.webp' },
  { key: 'radio_155', name: 'Szünet Rádió', streamUrl: 'http://92.61.114.191:1101/listen.mp3', logo: 'http://files.szunetradio.webnode.hu/200000011-7b3fe7c394/200/Sz%C3%BCnet%20R%C3%A1di%C3%B3%20logo.PNG' },
  { key: 'radio_156', name: 'Táska Rádió', streamUrl: 'http://live.taskaradio.com:7070/;stream.nsv#.mp3', logo: 'https://i1.wp.com/www.taskaradio.com/wp-content/uploads/2017/01/cropped-taska_radio_favicon_2_V2.png?fit=270%2C270' },
  { key: 'radio_157', name: 'Tilos Rádió', streamUrl: 'http://stream.tilos.hu/tilos_32.mp3', logo: 'https://tilos.hu/images/kockalogo.png' },
  { key: 'radio_158', name: 'Tilos Rádió 90.3', streamUrl: 'http://stream.tilos.hu/tilos', logo: 'https://tilos.hu/images/kockalogo.png' },
  { key: 'radio_159', name: 'Tilos Rádió Mesék', streamUrl: 'http://stream.tilos.hu/mese', logo: 'https://tilos.hu/images/kockalogo.png' },
  { key: 'radio_160', name: 'Tilos Rádió Okosodj!', streamUrl: 'http://stream.tilos.hu/szoveg', logo: 'https://tilos.hu/images/kockalogo.png' },
  { key: 'radio_161', name: 'Zemplén 104.9', streamUrl: 'https://stream.42netmedia.com:8443/zemplenfm', logo: 'https://pbs.twimg.com/profile_images/1481260801558253576/4UC-9oGk_400x400.jpg' },
  { key: 'radio_162', name: 'ZugRádió', streamUrl: 'http://zuglofm.netregator.hu:7812/zuglofm128.mp3', logo: 'https://zugradio.hu/wp-content/uploads/2018/04/logo224OK-2.png' },
];